// react/app/src/components/RecordTable.js
import React, { useState } from 'react';
import './RecordTable.css';
import ErrorPopover from './ErrorPopover';

function RecordTable(props) {
    const [filteredRecords, setFilteredRecords] = useState(props.records);
    const [activeFilter, setActiveFilter] = useState('all');

    const recordTableItems = filteredRecords.map(item => {
        const isUnique = item.isUniqueReference === true ? '' : <ErrorPopover message={item.isUniqueReference} />;
        const isValidDiscount = item.isValidDiscount === true ? '' : <ErrorPopover message={item.isValidDiscount} />;
        const isValidStartAmount = item.isValidStartAmount === true ? '' : <ErrorPopover message={item.isValidStartAmount} />;
        const isValidTotalAmount = item.isValidTotalAmount === true ? '' : <ErrorPopover message={item.isValidTotalAmount} />;

        return (
            <tr>
                <td>{item.record.reference} {isUnique} </td>
                <td>{item.record.name} </td>
                <td>{item.record.phoneNumber}</td>
                <td>{item.record.subscription}</td>
                <td>€ {item.record.startAmount} {isValidStartAmount} </td>
                <td>{Number.isInteger(item.record.discount) ? '€ ' + item.record.discount : item.record.discount * 100 + '%'} {isValidDiscount}</td>
                <td>€ {item.record.totalAmount} {isValidTotalAmount} </td>
            </tr>
        )
    })

    function handleFilterRecords(e) {
        const filter = e.target.value;

        if (filter === 'all') {
            setActiveFilter('all');
            setFilteredRecords(props.records);
        }
        if (filter === 'valid') {
            setActiveFilter('valid');
            setFilteredRecords(props.records.filter(item => item.isUniqueReference === true && item.isValidTotalAmount === true))
        }
        if (filter === 'invalid') {
            setActiveFilter('invalid');
            setFilteredRecords(props.records.filter(item => item.isUniqueReference !== true || item.isValidTotalAmount !== true))
        }
    }

    return (
        <>
            <h1>Record list</h1>

            <table className="record-table">
                <thead>
                    <tr>
                        <th colSpan="8">
                            <div className="table-filter">
                                <button onClick={handleFilterRecords} className={activeFilter === 'all' ? 'active-filter': ''} value="all">All records</button>
                                <button onClick={handleFilterRecords} className={activeFilter === 'valid' ? 'active-filter': ''} value="valid">Valid records</button>
                                <button onClick={handleFilterRecords} className={activeFilter === 'invalid' ? 'active-filter': ''} value="invalid">Invalid records</button>
                            </div>
                            <p>Number of records {filteredRecords.length}</p>
                        </th>
                    </tr>
                    <tr>
                        <th>Reference</th>
                        <th>Name</th>
                        <th>Phone number</th>
                        <th>Subscription</th>
                        <th>Amount</th>
                        <th>Discount</th>
                        <th>Total amount</th>
                    </tr>
                </thead>
                <tbody>
                    {recordTableItems}
                </tbody>
            </table>
        </>
    );
}

export default RecordTable;

// angular/app/src/app/record-table/record-table.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-record-table',
  templateUrl: './record-table.component.html',
  styleUrls: ['./record-table.component.css']
})
export class RecordTableComponent implements OnInit {
  @Input() records: Array<any>;
  activeFilter: string = 'all';
  filteredRecords: Array<any>;

  constructor() { }

  ngOnInit(): void {
    this.filteredRecords = this.records;
  }

  handleFilterRecords(filter: string) {

    if (filter === 'all') {
      this.activeFilter = 'all';
      this.filteredRecords = this.records;
    }
    if (filter === 'valid') {
      this.activeFilter = 'valid';
      this.filteredRecords = this.records.filter(item => item.isUniqueReference === true && item.isValidTotalAmount === true);
    }
    if (filter === 'invalid') {
      this.activeFilter = 'invalid';
      this.filteredRecords = this.records.filter(item => item.isUniqueReference !== true || item.isValidTotalAmount !== true);
    }
  }

  transformDiscount(discount: number): string {
    return Number.isInteger(discount) ? '€ ' + discount : discount * 100 + '%';
  }

}

<h1>Record list</h1>

<table className="record-table">
    <thead>
        <tr>
            <th colSpan="8">
                <div className="table-filter">
                    <button (click)="handleFilterRecords($event.target.value)" [ngClass]="{'active-filter': activeFilter === 'all'}" value="all">All records</button>
                    <button (click)="handleFilterRecords($event.target.value)" [ngClass]="{'active-filter': activeFilter === 'valid'}" value="valid">Valid records</button>
                    <button (click)="handleFilterRecords($event.target.value)" [ngClass]="{'active-filter': activeFilter === 'invalid'}" value="invalid">Invalid records</button>
                </div>
                <p>Number of records {{ filteredRecords.length }}</p>
            </th>
        </tr>
        <tr>
            <th>Reference</th>
            <th>Name</th>
            <th>Phone number</th>
            <th>Subscription</th>
            <th>Amount</th>
            <th>Discount</th>
            <th>Total amount</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let item of filteredRecords">
            <td>{{ item.record.reference }} <app-error-popover *ngIf="item.isUniqueReference != true" message={{item.isUniqueReference}}></app-error-popover></td>
            <td>{{ item.record.name }} </td>
            <td>{{ item.record.phoneNumber }}</td>
            <td>{{ item.record.subscription }}</td>
            <td>€ {{ item.record.startAmount }} <app-error-popover *ngIf="item.isValidStartAmount != true" message={{item.isValidStartAmount}}></app-error-popover></td>
            <td>{{ transformDiscount(item.record.discount) }} <app-error-popover *ngIf="item.isValidDiscount != true" message={{item.isValidDiscount}}></app-error-popover></td>
            <td>€ {{ item.record.totalAmount }} <app-error-popover *ngIf="item.isValidTotalAmount != true" message={{item.isValidTotalAmount}}></app-error-popover></td>
        </tr>
    </tbody>
</table>
